### ISSUE TITLE
New question/answer rollback check.

### ISSUE THREAD

**Issue by GrumpyCrouton** [SOBotics/Belisarius#1]
Earlier today in SOBotics, [Badger stated there was a new Cleanup badge awarded](https://chat.stackoverflow.com/transcript/message/40891662#40891662).

The "cleanup" in question is relevant to [Configuring Spring Cloud Config Server and Spring Cloud Vault for production](https://stackoverflow.com/questions/42077583/configuring-spring-cloud-config-server-and-spring-cloud-vault-for-production/48320998#48320998).

Now, once I saw that edit, I rolled back the "cleanup" that was performed, as it was the OP of the question rolling back an edit (That was approved through the suggested edits queue) that just put their code inside a code block. The OP rolled this back to take the code OUT of the code block.

Specifically, my idea is the bot should check if posts have an edit reason **containing** _"Edit approval overridden"_, which that one did. I think this would allow us to catch a lot of people rolling back edits that fix an issue with their post, thus harming their posts. 

I understand that this edit was caught by Badger, but that is only because it was the users FIRST rollback, and subsequent rollbacks or harmful edits the OP could make would not be caught the 2nd time or on any future posts.

**Comment by Bhargav-Rao** [comment]
Yeah, this is quite easy to do. Beli already reads through edit summaries, adding the word there would not be a hard work, atleast for the SD point of view. 

The way to get about it would be to [have a similar logic as the `OffensiveWordFilter`](https://github.com/SOBotics/Belisarius/blob/master/src/bugs/stackoverflow/belisarius/filters/OffensiveWordFilter.java), and using a [`LOW` severity](https://github.com/SOBotics/Belisarius/blob/912827d7efeb2b9c286fb8c193baa823ccbac038/src/bugs/stackoverflow/belisarius/filters/Filter.java#L8). Would perhaps take an hour at maximum to do it. 

I am more concerned about the false positives on the same. Are there a lot of invalid rollbacks for us to monitor, or is the number sufficiently low enough for us to ignore? 

I think we can run it for a month or so, and monitor the false positives, after which we can either keep the filter going as it is, make some changes or remove it completely.

**Comment by GrumpyCrouton** [comment]
I think monitoring it is a great idea. In chat Florern said 

> actually all rollbacks of suggested edits I've seen were bad.. so I'm pretty sure that'd be useful

I believe there is enough true positives that this would be an effective edition.
