### ISSUE TITLE
A dashboard for Belisarius 

### ISSUE THREAD

**Issue by Bhargav-Rao** [SOBotics/Belisarius#2]
Now that @rjrudman has implemented Higgs, we can try to <s>break</s> test Higgs out by creating a dashboard for Beli. Beli doesn't need a dashboard as such, because the revisions are always visible, but hey, why not have one. 

We need to have a nice name for the dashboard. Do add suggestions as comments below, and we can use the GH reactions to vote on them.

**Comment by K-Davis1** [comment]
BeliDash

**Comment by Bhargav-Rao** [comment]
Hippo

A reference to the place where the [vandals were defeated by Belisarius](https://en.wikipedia.org/wiki/Hippo_Regius)

**Comment by Fortunate-MAN** [comment]
> Titan

No real relation; just came to my mind.

**Comment by Jinx88909** [comment]
Name has been agreed as Hippo. Development is now well underway.
